### ISSUE TITLE
Attach a screenshot or interactive demo

### ISSUE THREAD

**Issue by top-kat** [alelapi/material-ui-player#204]
Hi, thanks a lot for this cool project! 

However, the fact that there are no screenshots or live demo makes is really frustrating. Having one of those could make people more confident and more willing to download the project.

Hope this is relevant :)

**Comment by alelapi** [comment]
Hi @top-kat , 
you are right, I didn't add any screenshots but I've actually added a live demo with a storyboard (check the About section  [alelapi.github.io/material-ui-player/](https://alelapi.github.io/material-ui-player/)).
Anyway, a screenshot or gif could be useful. Thank for the suggestion

**Comment by top-kat** [comment]
Wow perfect. I think the link could gain to be referenced in the readme or am I wrong ?

**Comment by alelapi** [comment]
> Wow perfect. I think the link could gain to be referenced in the readme or am I wrong ?

Yeah, I've added it
