### ISSUE TITLE
Basic usage gives TypeError

### ISSUE THREAD

**Issue by DoubleDebug** [alelapi/material-ui-player#229]
Tried using the package today and the basic usage of the VideoCard component gave me a TypeError.

- I created a sandbox [here](https://codesandbox.io/s/material-ui-player-bug-f4kbbr?file=/src/App.js).
- Screenshots are attached bellow

![err1](https://user-images.githubusercontent.com/62041862/164029178-b83d2423-8666-436a-a99d-11450d517632.png)
![err2](https://user-images.githubusercontent.com/62041862/164029184-e71352b5-50fd-4737-823d-96203a7fa06d.png)

**Comment by alelapi** [comment]
Thanks for letting me know @DoubleDebug, I feel that it's probably related to React 18 but I'll do some digging on it

**Comment by alelapi** [comment]
Not a bug. 
I didn't notice that you didn't provide a `ThemeProvider`, maybe I should write it in the README but I took it for granted if you use MaterialUI.
Also, you are using different version of @mui/styles and @mui/material
Here your [sandbox](https://codesandbox.io/s/material-ui-player-bug-forked-x2xjvx) corrected

**Comment by DoubleDebug** [comment]
Makes sense. Thanks for the reply!
Would be nice if there was a note in the README about it.
