### ISSUE TITLE
Player does not work in mobile devices

### ISSUE THREAD

**Issue by Molnfront** [alelapi/material-ui-player#317]
If I emulate a mobile device in Chrome the Soundbutton will not work.

I tried it in a working codesandbox and could repeat the issue both with Soundbutton and video player:

 https://codesandbox.io/s/material-ui-player-bug-forked-x2xjvx?file=/package.json:245-256

**Comment by alelapi** [comment]
Hi @Molnfront , what do you mean by `will not work`?
I'm testing your sandbox and it works.. even [this](https://codesandbox.io/s/material-ui-player-bug-forked-wmp9s8?file=/src/App.js:282-313) with SoundButton it's working fine

**Comment by Molnfront** [comment]
Yeah I checked it again and it's working in the sandbox. But not in my own app. Don't know why, I have no error anywhere. The sound button works in web browser, but not in emulated phone devices.

I use the soundbutton inside a map with swipe cards.

**Comment by Molnfront** [comment]
Hm, I need to add the className="pressable" to the soundbutton for it to work in a react-tinder-card. Now the problem is to figure out how to do this in mui..

**Comment by alelapi** [comment]
Ok, so it's not an issue related to this library, as it is specified in the doc of react-tinder-card https://github.com/3DJakob/react-tinder-card#buttons-inside-a-tindercard

**Comment by Molnfront** [comment]
Yes!
